# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 张强
email: inteli_zq@163.com
description: 儿子问爸爸：我为什么要读书？
             爸爸回答说：我这么跟你说吧。你读了书，你在评价金融项目的时候就会知道什么是跨界思维、裂变思维、杠杆思维、创新思维、大数据思维、复利倍增思维、共享经济思维分享经济思维。如果你没有读书，你只会说一句“卧槽，传销吧”。
welcome_message: welcome to the old man's horse farm
url: "http://arch-long.cn"

# 头像里面的标题
avatarTitle: archLong
# 头像里面的描述
avatarDesc: Spark / Scala


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}


twitter_username: None
github_username:  PerfectZQ

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  extensions:
      - autolink
      - footnotes
      - smart
highlighter: rouge

theme: minima

# Pagination
gems: [jekyll-paginate,jekyll-sitemap,jekyll-assets,rouge]
paginate: 20
paginate_path: "page/:num/"

exclude:
  - Gemfile
  - Gemfile.lock
